// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetTaskByID(arg1) {
  return window['go']['main']['App']['GetTaskByID'](arg1);
}
