// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateTask(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function GetAllTasks():Promise<Array<types.Task>>;

export function GetTaskByID(arg1:string):Promise<types.Task>;
